name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Copy files to root directory
        run: |
          cp -R * $GITHUB_WORKSPACE/
          rm -rf $GITHUB_WORKSPACE/*
          mv $GITHUB_WORKSPACE/build/* $GITHUB_WORKSPACE/
          rm -rf $GITHUB_WORKSPACE/build/
      - name: Configure git
        run: |
          git config --global user.email "mappiapps@gmail.com"
          git config --global user.name "mappimaps"
      - name: Add files
        run: |
          git add -A
      - name: Commit files
        run: |
          git commit -m "Deploy to GitHub Pages"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          force: true
