name: Deploy to gh-pages

on:
  push:
    branches:
      - [NOMBRE_DE_TU_RAMA]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout gh-pages
          rm -rf ./*
          cp -r * ./.github/workflows/ # Copia todo menos la carpeta .github
          git add -A .
          git commit -m "Deploy via GitHub Actions"
          git push -f origin gh-pages
