name: Deploy

on:
  push:
    branches:
      - gh-pages # Cambia "main" por el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # Cambia "gh-pages" por la rama donde quieres publicar tu contenido
          folder: ./ # Cambia "build" por la carpeta donde se encuentra tu build generado con "npm run build"
