name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # cambia por la rama en la que tengas los archivos a desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy files to root directory
        run: |
          rm -rf *
          cp -r ${{ github.workspace }}/build/* .
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: .
