name: Deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Copy build to gh-pages branch
        run: |
          git add .
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -m "Deploying to gh-pages"
          git push origin gh-pages
