name: Deploy to GitHub Pages
on:
  push:
    branches:
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: .
          clean: true
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
